FROM apache/airflow:3.1.1-python3.12

USER root
RUN apt-get update && apt-get install -y gcc g++
USER airflow

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/opt/airflow:$PYTHONPATH